[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin"
    Content-Security-Policy-Report-Only = "default-src https: 'unsafe-inline' 'unsafe-eval'; report-uri: https://report.chaoscosmos.pl; report-to: csp-endpoint"